# Generated by Django 4.2.30 on 2026-04-21 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherrecord',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
