# Generated by Django 4.2.30 on 2026-04-21 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_weatherrecord_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherrecord',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weatherrecord',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
